// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdffpyeesafsejfmzwvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZmZweWVlc2Fmc2VqZm16d3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDA2ODcsImV4cCI6MjA1MjAxNjY4N30.fzRXTg_yy2pDDPAaAnJdmrfSERo5NmyVRqN-kzFhP6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);